import dotenv from "dotenv";
import postgres from "postgres";
import { hashPassword } from "../lib/auth";

dotenv.config({ path: ".env.local" });
dotenv.config();

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  throw new Error("DATABASE_URL is not set (expected in .env.local)");
}

const sql = postgres(databaseUrl, {
  ssl: { rejectUnauthorized: false },
});

async function migrate() {
  await sql`CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE,
    role TEXT CHECK(role IN ('factory', 'buyer', 'admin')),
    company_name TEXT,
    wechat_id TEXT,
    mobile_number TEXT,
    whatsapp_number TEXT,
    is_approved BOOLEAN DEFAULT FALSE
  )`;

  await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash TEXT`;
  await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT FALSE`;
  await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS approval_status TEXT DEFAULT 'pending_verification'`;
  await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS approval_note TEXT`;
  await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ`;
  await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS disapproved_at TIMESTAMPTZ`;
  await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN DEFAULT FALSE`;
  await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_views INTEGER DEFAULT 0`;
  await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW()`;

  await sql`CREATE INDEX IF NOT EXISTS idx_users_role ON users(role)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_users_is_approved ON users(is_approved)`;

  await sql`CREATE TABLE IF NOT EXISTS email_verification_tokens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token TEXT UNIQUE NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`;

  await sql`CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    description TEXT,
    specifications TEXT,
    photo TEXT,
    factory_price_cny DOUBLE PRECISION,
    buyer_price_inr DOUBLE PRECISION,
    status TEXT DEFAULT 'draft',
    factory_id INTEGER REFERENCES users(id),
    category TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`;

  await sql`CREATE INDEX IF NOT EXISTS idx_products_factory_id ON products(factory_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_products_status ON products(status)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_products_category ON products(category)`;

  await sql`CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER REFERENCES products(id),
    buyer_id INTEGER REFERENCES users(id),
    quantity INTEGER,
    status TEXT DEFAULT 'pending',
    rejection_reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`;

  await sql`CREATE INDEX IF NOT EXISTS idx_orders_product_id ON orders(product_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_orders_buyer_id ON orders(buyer_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status)`;

  await sql`CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    message TEXT NOT NULL,
    type TEXT,
    related_id INTEGER,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`;

  await sql`CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications(is_read)`;

  await sql`CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT
  )`;

  await sql`CREATE TABLE IF NOT EXISTS custom_orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id INTEGER REFERENCES users(id),
    photo TEXT,
    requirements TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`;

  await sql`CREATE INDEX IF NOT EXISTS idx_custom_orders_buyer_id ON custom_orders(buyer_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_custom_orders_status ON custom_orders(status)`;

  await sql`CREATE TABLE IF NOT EXISTS custom_order_proposals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    custom_order_id INTEGER REFERENCES custom_orders(id),
    factory_id INTEGER REFERENCES users(id),
    photo TEXT,
    description TEXT,
    price_cny DOUBLE PRECISION,
    price_inr DOUBLE PRECISION,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`;

  await sql`ALTER TABLE custom_order_proposals ADD COLUMN IF NOT EXISTS production_time INTEGER`;
  await sql`ALTER TABLE custom_order_proposals ADD COLUMN IF NOT EXISTS notes TEXT`;

  await sql`CREATE INDEX IF NOT EXISTS idx_custom_order_proposals_order_id ON custom_order_proposals(custom_order_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_custom_order_proposals_factory_id ON custom_order_proposals(factory_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_custom_order_proposals_status ON custom_order_proposals(status)`;

  await sql`CREATE TABLE IF NOT EXISTS reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER REFERENCES orders(id),
    product_id INTEGER REFERENCES products(id),
    factory_id INTEGER REFERENCES users(id),
    buyer_id INTEGER REFERENCES users(id),
    rating INTEGER,
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`;

  await sql`CREATE INDEX IF NOT EXISTS idx_reviews_product_id ON reviews(product_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_reviews_factory_id ON reviews(factory_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_reviews_buyer_id ON reviews(buyer_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_reviews_order_id ON reviews(order_id)`;

  await sql`CREATE TABLE IF NOT EXISTS messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    custom_order_id INTEGER REFERENCES custom_orders(id),
    sender_id INTEGER REFERENCES users(id),
    receiver_id INTEGER REFERENCES users(id),
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`;

  await sql`CREATE INDEX IF NOT EXISTS idx_messages_custom_order_id ON messages(custom_order_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_messages_sender_id ON messages(sender_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_messages_receiver_id ON messages(receiver_id)`;

  await sql`INSERT INTO settings (key, value)
    VALUES ('exchange_rate', '12.0')
    ON CONFLICT (key) DO NOTHING`;
  await sql`INSERT INTO settings (key, value)
    VALUES ('admin_markup', '1.2')
    ON CONFLICT (key) DO NOTHING`;

  const [{ count }] = await sql<{ count: number }[]>`SELECT COUNT(*)::int as count FROM users`;
  if (count === 0) {
    await sql`INSERT INTO users (email, role) VALUES ('admin@lumina.com', 'admin')`;
    await sql`INSERT INTO users (email, role) VALUES ('factory@china.com', 'factory')`;
    await sql`INSERT INTO users (email, role) VALUES ('buyer@india.com', 'buyer')`;
  }

  const demoPasswordHash = hashPassword("demo12345");
  await sql`
    UPDATE users
    SET
      password_hash = COALESCE(password_hash, ${demoPasswordHash}),
      email_verified = TRUE,
      approval_status = CASE
        WHEN role = 'admin' THEN 'approved'
        WHEN approval_status = 'disapproved' THEN approval_status
        ELSE 'approved'
      END,
      is_approved = CASE WHEN role = 'admin' THEN TRUE ELSE COALESCE(is_approved, TRUE) END,
      approved_at = COALESCE(approved_at, NOW()),
      must_change_password = FALSE
    WHERE email IN ('admin@lumina.com', 'factory@china.com', 'buyer@india.com')
  `;
}

migrate()
  .then(() => {
    console.log("Database migration complete");
  })
  .catch((error) => {
    console.error("Database migration failed:", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await sql.end({ timeout: 5 });
  });
